## Markdown Linter rules ##

# - https://github.com/DavidAnson/markdownlint

MD007:
  indent: 2 # ul-indent
MD009: false # no-trailing-spaces
MD010: false # no-hard-tabs
MD012: false # no-multiple-blanks
MD013:
  line_length: 808 # line-length
MD022: false # blanks-around-headings
MD026:
  punctuation: ".,;:!。，；:" # no-trailing-punctuation
MD029: false # ol-prefix
MD031: false # blanks-around-fences
MD032: false # blanks-around-lists
MD033: false # no-inline-html
MD034: false # no-bare-urls
